version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data/:data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/digix
    restart: always
    command: bash -c "yarn --only=prod && yarn dev"
    volumes:
      - ./dist/:/usr/src/digix/dist/
      - ./package.json:/usr/src/digix/package.json
    ports:
      - "3333:3333"
    links:
      - mongo
